// frontend/src/views/DatasourceList.tsx
import { useEffect, useState } from 'react'
import type { ColumnDef } from '@tanstack/react-table'
import { LogIn } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import DataTable from '@/components/DataTable'
import { getDatasources, deployDatasource } from '@/api'
import { useNotify } from '@/notify'
import { truncate, formatDate } from '@/logic/format'
import type { Datasource } from '@/types'

export default function DatasourceList() {
  const notify = useNotify()
  const [datasources, setDatasources] = useState<Datasource[]>([])
  const [dialogOpen, setDialogOpen] = useState(false)
  const [selectedDatasource, setSelectedDatasource] = useState<Datasource | null>(null)
  const [targetDeployment, setTargetDeployment] = useState<number | null>(null)

  useEffect(() => {
    getDatasources()
      .then(setDatasources)
      .catch(() => notify.error('Error connecting with the server'))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function openSendDialog(datasource: Datasource) {
    setSelectedDatasource(datasource)
    setTargetDeployment(null)
    setDialogOpen(true)
  }

  async function send() {
    if (!selectedDatasource) return
    const data = { ...selectedDatasource, deployment: String(targetDeployment) }
    setDialogOpen(false)
    try {
      await deployDatasource(data)
      notify.ok('Datasource sent to Kafka. Refresh the page in a while to see it')
    } catch (err) {
      notify.error('Error sending the datasource: ' + (err as Error).message)
    }
  }

  const columns: ColumnDef<Datasource, unknown>[] = [
    { accessorKey: 'description', header: 'Description', enableSorting: false },
    { accessorKey: 'deployment', header: 'Deployment' },
    { accessorKey: 'input_format', header: 'Input format', enableSorting: false },
    {
      id: 'input_config',
      header: 'Input configuration',
      enableSorting: false,
      cell: ({ row }) => <span title={row.original.input_config}>{truncate(row.original.input_config, 10)}</span>,
    },
    { accessorKey: 'topic', header: 'Kafka topic', enableSorting: false },
    { accessorKey: 'validation_rate', header: 'Validation rate', enableSorting: false },
    { accessorKey: 'test_rate', header: 'Test rate', enableSorting: false },
    { accessorKey: 'total_msg', header: 'Total msg', enableSorting: false },
    {
      accessorKey: 'time',
      header: 'Time',
      cell: ({ row }) => formatDate(row.original.time),
    },
    {
      id: 'send',
      header: 'Send again',
      enableSorting: false,
      cell: ({ row }) => (
        <Button variant="ghost" size="icon" title="Send again to another deployment" onClick={() => openSendDialog(row.original)}>
          <LogIn className="size-4" />
        </Button>
      ),
    },
  ]

  return (
    <div className="space-y-4">
      <h1 className="text-xl font-semibold">Datasources received</h1>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Send datasource to deployment</DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground">
            Please, make sure that the timestamp of the datasource is less than KAFKA_LOG_RETENTION_DAYS. Otherwise, the
            datasource could have been deleted from Kafka.
          </p>
          <div className="space-y-1.5">
            <Label>Deployment ID *</Label>
            <Input
              type="number"
              value={targetDeployment ?? ''}
              onChange={(e) => setTargetDeployment(e.target.value === '' ? null : Number(e.target.value))}
            />
          </div>
          <DialogFooter>
            <Button variant="ghost" onClick={() => setDialogOpen(false)}>
              Cancel
            </Button>
            <Button disabled={targetDeployment == null} onClick={send}>
              Send
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <DataTable columns={columns} data={datasources} />
    </div>
  )
}

// frontend-vue/src/views/DatasourceList.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'
import InputText from 'primevue/inputtext'
import InputNumber from 'primevue/inputnumber'
import Button from 'primevue/button'
import Dialog from 'primevue/dialog'
import { FilterMatchMode } from 'primevue/api'
import { getDatasources, deployDatasource } from '../api'
import { useNotify } from '../notify'
import { truncate } from '../logic/format'
import type { Datasource } from '../types'

const notify = useNotify()

const datasources = ref<Datasource[]>([])
const filters = ref({ global: { value: null as string | null, matchMode: FilterMatchMode.CONTAINS } })

onMounted(async () => {
  try {
    datasources.value = await getDatasources()
  } catch {
    notify.error('Error connecting with the server')
  }
})

const dialogVisible = ref(false)
const selectedDatasource = ref<Datasource | null>(null)
const targetDeployment = ref<number | null>(null)

function openSendDialog(datasource: Datasource) {
  selectedDatasource.value = datasource
  targetDeployment.value = null
  dialogVisible.value = true
}

async function send() {
  if (!selectedDatasource.value) return
  const data = { ...selectedDatasource.value, deployment: String(targetDeployment.value) }
  dialogVisible.value = false
  try {
    await deployDatasource(data)
    notify.ok('Datasource sent to Kafka. Refresh the page in a while to see it')
  } catch (err) {
    notify.error('Error sending the datasource: ' + (err as Error).message)
  }
}
</script>

<template>
  <div class="page">
    <div class="page-header">
      <h1>Datasources received</h1>
    </div>

    <Dialog
      v-model:visible="dialogVisible"
      header="Send datasource to deployment"
      modal
      style="max-width: 420px"
    >
      <p>
        Please, make sure that the timestamp of the datasource is less than
        KAFKA_LOG_RETENTION_DAYS. Otherwise, the datasource could have been deleted from Kafka.
      </p>
      <div class="field">
        <label>Deployment ID *</label>
        <InputNumber v-model="targetDeployment" :useGrouping="false" />
      </div>
      <template #footer>
        <Button label="Cancel" text @click="dialogVisible = false" />
        <Button label="Send" :disabled="targetDeployment == null" @click="send" />
      </template>
    </Dialog>

    <DataTable :value="datasources" v-model:filters="filters" paginator :rows="10" class="surface">
      <template #header>
        <InputText v-model="filters.global.value" placeholder="Filter" />
      </template>
      <Column field="description" header="Description" />
      <Column field="deployment" header="Deployment" sortable />
      <Column field="input_format" header="Input format" />
      <Column header="Input configuration">
        <template #body="{ data }">
          <span :title="data.input_config">{{ truncate(data.input_config, 10) }}</span>
        </template>
      </Column>
      <Column field="topic" header="Kafka topic" />
      <Column field="validation_rate" header="Validation rate" />
      <Column field="test_rate" header="Test rate" />
      <Column field="total_msg" header="Total msg" />
      <Column field="time" header="Time" sortable />
      <Column header="Send again">
        <template #body="{ data }">
          <Button
            icon="pi pi-sign-in"
            text
            title="Send again to another deployment"
            @click="openSendDialog(data)"
          />
        </template>
      </Column>
    </DataTable>
  </div>
</template>
