// frontend/src/views/IoTDeviceView.tsx
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { getIoTDevice, createIoTDevice, editIoTDevice } from '@/api'
import { useNotify } from '@/notify'

interface FormState {
  friendly_name: string
  mqtt_address: string
  mqtt_port: number | string
  mqtt_username: string
  mqtt_password: string
}

const emptyForm: FormState = {
  friendly_name: '',
  mqtt_address: '',
  mqtt_port: '',
  mqtt_username: '',
  mqtt_password: '',
}

export default function IoTDeviceView() {
  const { id } = useParams()
  const navigate = useNavigate()
  const notify = useNotify()

  const deviceId = id ? Number(id) : undefined
  const create = deviceId === undefined
  const [valid, setValid] = useState(true)
  const [form, setForm] = useState<FormState>(emptyForm)
  const [showPassword, setShowPassword] = useState(false)

  useEffect(() => {
    let cancelled = false
    async function load() {
      if (!create && deviceId !== undefined) {
        try {
          const device = await getIoTDevice(deviceId)
          if (cancelled) return
          setForm({
            friendly_name: device.friendly_name,
            mqtt_address: device.mqtt_address,
            mqtt_port: device.mqtt_port,
            mqtt_username: device.mqtt_username,
            mqtt_password: device.mqtt_password,
          })
        } catch {
          if (!cancelled) {
            setValid(false)
            notify.error('Error IoT Device not found')
          }
        }
      }
    }
    load()
    return () => {
      cancelled = true
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [deviceId])

  function set<K extends keyof FormState>(key: K, value: FormState[K]) {
    setForm((prev) => ({ ...prev, [key]: value }))
  }

  const formInvalid = !form.friendly_name

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault()
    try {
      if (create) {
        await createIoTDevice(form)
        notify.ok('IoT Device created')
      } else if (deviceId !== undefined) {
        await editIoTDevice(deviceId, form)
        notify.ok('IoT Device updated')
      }
      navigate('/devices')
    } catch (err) {
      notify.error(`Error ${create ? 'creating' : 'updating'} the IoT Device: ` + (err as Error).message)
    }
  }

  return (
    <div className="mx-auto max-w-2xl">
      <Card>
        <CardHeader>
          <CardTitle>{create ? 'Create IoT Device' : 'Edit IoT Device'}</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} autoComplete="off" className="space-y-5">
            <div className="space-y-1.5">
              <Label>Friendly Name *</Label>
              <Input autoFocus value={form.friendly_name} onChange={(e) => set('friendly_name', e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label>MQTT Address</Label>
              <Input value={form.mqtt_address} onChange={(e) => set('mqtt_address', e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label>MQTT Port</Label>
              <Input value={form.mqtt_port} onChange={(e) => set('mqtt_port', e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label>MQTT User</Label>
              <Input value={form.mqtt_username} onChange={(e) => set('mqtt_username', e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label>MQTT Password</Label>
              <div className="flex gap-2">
                <Input
                  type={showPassword ? 'text' : 'password'}
                  value={form.mqtt_password}
                  onChange={(e) => set('mqtt_password', e.target.value)}
                />
                <Button type="button" variant="outline" onClick={() => setShowPassword((v) => !v)}>
                  {showPassword ? 'Hide' : 'Show'}
                </Button>
              </div>
            </div>

            <div className="flex justify-between border-t pt-4">
              <Button type="button" variant="ghost" onClick={() => navigate(-1)}>
                Go Back
              </Button>
              {valid && (
                <Button type="submit" disabled={formInvalid}>
                  {create ? 'Create' : 'Edit'}
                </Button>
              )}
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}

// frontend-vue/src/views/IoTDeviceView.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Card from 'primevue/card'
import InputText from 'primevue/inputtext'
import Password from 'primevue/password'
import Button from 'primevue/button'
import { getIoTDevice, createIoTDevice, editIoTDevice } from '../api'
import { useNotify } from '../notify'

const route = useRoute()
const router = useRouter()
const notify = useNotify()

const deviceId = route.params.id ? Number(route.params.id) : undefined
const create = deviceId === undefined
const valid = ref(true)

const form = ref({
  friendly_name: '',
  mqtt_address: '',
  mqtt_port: '' as number | string,
  mqtt_username: '',
  mqtt_password: ''
})

onMounted(async () => {
  if (!create && deviceId !== undefined) {
    try {
      const device = await getIoTDevice(deviceId)
      form.value = {
        friendly_name: device.friendly_name,
        mqtt_address: device.mqtt_address,
        mqtt_port: device.mqtt_port,
        mqtt_username: device.mqtt_username,
        mqtt_password: device.mqtt_password
      }
    } catch {
      valid.value = false
      notify.error('Error IoT Device not found')
    }
  }
})

const formInvalid = computed(() => !form.value.friendly_name)

async function onSubmit() {
  try {
    if (create) {
      await createIoTDevice(form.value)
      notify.ok('IoT Device created')
    } else if (deviceId !== undefined) {
      await editIoTDevice(deviceId, form.value)
      notify.ok('IoT Device updated')
    }
    router.push('/devices')
  } catch (err) {
    notify.error(`Error ${create ? 'creating' : 'updating'} the IoT Device: ` + (err as Error).message)
  }
}
</script>

<template>
  <div class="page">
    <Card class="form-card">
      <template #title>{{ create ? 'Create IoT Device' : 'Edit IoT Device' }}</template>
      <template #content>
        <form @submit.prevent="onSubmit" autocomplete="off">
          <div class="field">
            <label>Friendly Name *</label>
            <InputText v-model="form.friendly_name" autofocus />
          </div>
          <div class="field">
            <label>MQTT Address</label>
            <InputText v-model="form.mqtt_address" />
          </div>
          <div class="field">
            <label>MQTT Port</label>
            <InputText v-model="form.mqtt_port as string" />
          </div>
          <div class="field">
            <label>MQTT User</label>
            <InputText v-model="form.mqtt_username" />
          </div>
          <div class="field">
            <label>MQTT Password</label>
            <Password v-model="form.mqtt_password" :feedback="false" toggleMask />
          </div>

          <div class="row-buttons">
            <Button label="Go Back" text @click="$router.back()" />
            <Button
              v-if="valid"
              type="submit"
              :label="create ? 'Create' : 'Edit'"
              :disabled="formInvalid"
            />
          </div>
        </form>
      </template>
    </Card>
  </div>
</template>
