// frontend/src/views/ModelView.tsx
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import CodeEditor from '@/components/CodeEditor'
import { getModel, getDistributedModels, createModel, editModel } from '@/api'
import { useNotify } from '@/notify'
import type { Framework, ModelPayload, SimpleModel } from '@/types'

const TF_PLACEHOLDER = `model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])`

const PTH_PLACEHOLDER = `class NeuralNetwork(nn.Module):
    def __init__(self): ...
    def forward(self, x): ...
    def loss_fn(self): ...
    def optimizer(self): ...
    def metrics(self): ...

model = NeuralNetwork()`

interface FormState {
  name: string
  description: string
  framework: Framework | ''
  distributed: boolean
  father: number | null
  imports: string
  code: string
}

const emptyForm: FormState = {
  name: '',
  description: '',
  framework: '',
  distributed: false,
  father: null,
  imports: '',
  code: '',
}

export default function ModelView() {
  const { id } = useParams()
  const navigate = useNavigate()
  const notify = useNotify()

  const modelId = id ? Number(id) : undefined
  const create = modelId === undefined
  const [valid, setValid] = useState(true)
  const [form, setForm] = useState<FormState>(emptyForm)
  const [distributedModels, setDistributedModels] = useState<SimpleModel[]>([])

  useEffect(() => {
    let cancelled = false
    async function load() {
      if (!create && modelId !== undefined) {
        try {
          const model = await getModel(modelId)
          if (cancelled) return
          setForm({
            name: model.name,
            description: model.description,
            framework: model.framework,
            distributed: model.distributed,
            father: model.father ? model.father.id : null,
            imports: model.imports,
            code: model.code,
          })
        } catch {
          if (!cancelled) {
            setValid(false)
            notify.error('Error model not found')
          }
        }
      }
      try {
        const models = await getDistributedModels()
        if (!cancelled) setDistributedModels(models)
      } catch {
        if (!cancelled) notify.error('Error connecting with the server')
      }
    }
    load()
    return () => {
      cancelled = true
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [modelId])

  const placeholder = form.framework === 'tf' ? TF_PLACEHOLDER : form.framework === 'pth' ? PTH_PLACEHOLDER : ''
  const formInvalid = !form.name || !form.framework || !form.code

  function fatherName(fid: number | null): string {
    if (fid == null) return ''
    return distributedModels.find((m) => m.id === fid)?.name ?? ''
  }

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault()
    const payload: ModelPayload = {
      name: form.name,
      description: form.description,
      framework: form.framework as Framework,
      imports: form.imports,
      code: form.code,
    }
    // Distributed models are a TensorFlow-only feature (same as the old frontend).
    if (form.framework === 'tf') {
      payload.distributed = form.distributed
      if (form.distributed && form.father != null) payload.father = form.father
    }
    try {
      if (create) {
        await createModel(payload)
        notify.ok('Model created')
      } else if (modelId !== undefined) {
        await editModel(modelId, payload)
        notify.ok('Model updated')
      }
      navigate('/models')
    } catch (err) {
      notify.error(`Error ${create ? 'creating' : 'updating'} the model: ` + (err as Error).message)
    }
  }

  const fatherOptions = useMemo(
    () => distributedModels.filter((m) => m.id !== modelId),
    [distributedModels, modelId],
  )

  return (
    <div className="mx-auto max-w-2xl">
      <Card>
        <CardHeader>
          <CardTitle>{create ? 'Create Model' : `Edit Model ${modelId}`}</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} autoComplete="off" className="space-y-5">
            <div className="space-y-1.5">
              <Label htmlFor="name">Name *</Label>
              <Input
                id="name"
                autoFocus
                value={form.name}
                onChange={(e) => setForm({ ...form, name: e.target.value })}
              />
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="description">Description</Label>
              <Input
                id="description"
                value={form.description}
                onChange={(e) => setForm({ ...form, description: e.target.value })}
              />
            </div>

            <div className="space-y-2">
              <Label>Select ML Framework *</Label>
              <RadioGroup
                value={form.framework}
                onValueChange={(v) => setForm({ ...form, framework: v as Framework })}
                className="flex gap-6"
              >
                <label className="flex items-center gap-2 text-sm font-normal">
                  <RadioGroupItem value="tf" /> TensorFlow
                </label>
                <label className="flex items-center gap-2 text-sm font-normal">
                  <RadioGroupItem value="pth" /> PyTorch (Ignite)
                </label>
              </RadioGroup>
            </div>

            {form.framework === 'tf' && (
              <label className="flex items-center gap-2 text-sm font-normal">
                <Checkbox
                  checked={form.distributed}
                  onCheckedChange={(v) => setForm({ ...form, distributed: v === true })}
                />
                Distributed
              </label>
            )}

            {form.framework === 'tf' && form.distributed && (
              <div className="space-y-1.5">
                <Label>Upper model</Label>
                <Select
                  value={form.father != null ? String(form.father) : '__none__'}
                  onValueChange={(v) => setForm({ ...form, father: v === '__none__' ? null : Number(v) })}
                >
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="None (top of the chain)">
                      {form.father != null ? `ID${form.father} ${fatherName(form.father)}` : 'None (top of the chain)'}
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="__none__">None (top of the chain)</SelectItem>
                    {fatherOptions.map((m) => (
                      <SelectItem key={m.id} value={String(m.id)}>
                        ID{m.id} {m.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}

            <div className="space-y-1.5">
              <Label>Imports</Label>
              <CodeEditor
                value={form.imports}
                onChange={(v) => setForm({ ...form, imports: v })}
                language="python"
                height="90px"
                placeholder="import ..."
                ariaLabel="Imports"
              />
            </div>

            <div className="space-y-1.5">
              <Label>Code *</Label>
              <CodeEditor
                value={form.code}
                onChange={(v) => setForm({ ...form, code: v })}
                language="python"
                height="360px"
                placeholder={placeholder}
                ariaLabel="Model code"
              />
            </div>

            <div className="flex justify-between border-t pt-4">
              <Button type="button" variant="ghost" onClick={() => navigate(-1)}>
                Go Back
              </Button>
              {valid && (
                <Button type="submit" disabled={formInvalid}>
                  {create ? 'Create' : 'Edit'}
                </Button>
              )}
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}

// frontend-vue/src/views/ModelView.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Card from 'primevue/card'
import InputText from 'primevue/inputtext'
import RadioButton from 'primevue/radiobutton'
import Checkbox from 'primevue/checkbox'
import Dropdown from 'primevue/dropdown'
import Button from 'primevue/button'
import CodeEditor from '../components/CodeEditor.vue'
import { getModel, getDistributedModels, createModel, editModel } from '../api'
import { useNotify } from '../notify'
import type { Framework, ModelPayload, SimpleModel } from '../types'

const TF_PLACEHOLDER = `model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])`

const PTH_PLACEHOLDER = `class NeuralNetwork(nn.Module):
    def __init__(self): ...
    def forward(self, x): ...
    def loss_fn(self): ...
    def optimizer(self): ...
    def metrics(self): ...

model = NeuralNetwork()`

const route = useRoute()
const router = useRouter()
const notify = useNotify()

const modelId = route.params.id ? Number(route.params.id) : undefined
const create = modelId === undefined
const valid = ref(true)

const form = ref({
  name: '',
  description: '',
  framework: '' as Framework | '',
  distributed: false,
  father: null as number | null,
  imports: '',
  code: ''
})
const distributedModels = ref<SimpleModel[]>([])

onMounted(async () => {
  if (!create && modelId !== undefined) {
    try {
      const model = await getModel(modelId)
      form.value = {
        name: model.name,
        description: model.description,
        framework: model.framework,
        distributed: model.distributed,
        father: model.father ? model.father.id : null,
        imports: model.imports,
        code: model.code
      }
    } catch {
      valid.value = false
      notify.error('Error model not found')
    }
  }
  try {
    distributedModels.value = await getDistributedModels()
  } catch {
    notify.error('Error connecting with the server')
  }
})

const placeholder = computed(() => {
  if (form.value.framework === 'tf') return TF_PLACEHOLDER
  if (form.value.framework === 'pth') return PTH_PLACEHOLDER
  return ''
})

const formInvalid = computed(() => !form.value.name || !form.value.framework || !form.value.code)

function fatherName(id: number | null): string {
  if (id == null) return ''
  return distributedModels.value.find((m) => m.id === id)?.name ?? ''
}

async function onSubmit() {
  const f = form.value
  const payload: ModelPayload = {
    name: f.name,
    description: f.description,
    framework: f.framework as Framework,
    imports: f.imports,
    code: f.code
  }
  // Distributed models are a TensorFlow-only feature (same as the Angular form).
  if (f.framework === 'tf') {
    payload.distributed = f.distributed
    if (f.distributed && f.father != null) payload.father = f.father
  }
  try {
    if (create) {
      await createModel(payload)
      notify.ok('Model created')
    } else if (modelId !== undefined) {
      await editModel(modelId, payload)
      notify.ok('Model updated')
    }
    router.push('/models')
  } catch (err) {
    notify.error(`Error ${create ? 'creating' : 'updating'} the model: ` + (err as Error).message)
  }
}
</script>

<template>
  <div class="page">
    <Card class="form-card">
      <template #title>{{ create ? 'Create Model' : `Edit Model ${modelId}` }}</template>
      <template #content>
        <form @submit.prevent="onSubmit" autocomplete="off">
          <div class="field">
            <label for="name">Name *</label>
            <InputText id="name" v-model="form.name" autofocus />
          </div>

          <div class="field">
            <label for="description">Description</label>
            <InputText id="description" v-model="form.description" />
          </div>

          <div class="field">
            <label>Select ML Framework *</label>
            <div class="field-row">
              <label><RadioButton v-model="form.framework" value="tf" /> TensorFlow</label>
              <label><RadioButton v-model="form.framework" value="pth" /> PyTorch (Ignite)</label>
            </div>
          </div>

          <div class="field" v-if="form.framework === 'tf'">
            <label><Checkbox v-model="form.distributed" binary /> Distributed</label>
          </div>

          <div class="field" v-if="form.framework === 'tf' && form.distributed">
            <label>Upper model</label>
            <Dropdown
              v-model="form.father"
              :options="distributedModels"
              optionValue="id"
              showClear
              placeholder="None (top of the chain)"
            >
              <template #option="{ option }">ID{{ option.id }} {{ option.name }}</template>
              <template #value="{ value }">
                <span v-if="value != null">ID{{ value }} {{ fatherName(value) }}</span>
                <span v-else>None (top of the chain)</span>
              </template>
            </Dropdown>
          </div>

          <div class="field">
            <label for="imports">Imports</label>
            <CodeEditor v-model="form.imports" language="python" height="90px" placeholder="import ..." />
          </div>

          <div class="field">
            <label for="code">Code *</label>
            <CodeEditor v-model="form.code" language="python" height="360px" :placeholder="placeholder" />
          </div>

          <div class="row-buttons">
            <Button label="Go Back" text @click="$router.back()" />
            <Button
              v-if="valid"
              type="submit"
              :label="create ? 'Create' : 'Edit'"
              :disabled="formInvalid"
            />
          </div>
        </form>
      </template>
    </Card>
  </div>
</template>
