// frontend-vue/src/views/ConfigurationList.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useConfirm } from 'primevue/useconfirm'
import { useRouter } from 'vue-router'
import Card from 'primevue/card'
import InputText from 'primevue/inputtext'
import Button from 'primevue/button'
import Menu from 'primevue/menu'
import type { MenuItem } from 'primevue/menuitem'
import { getConfigurations, deleteConfiguration } from '../api'
import { useNotify } from '../notify'
import type { Configuration } from '../types'

const notify = useNotify()
const confirm = useConfirm()
const router = useRouter()

const configurations = ref<Configuration[]>([])
const filter = ref('')

onMounted(async () => {
  try {
    configurations.value = await getConfigurations()
  } catch {
    notify.error('Error connecting with the server')
  }
})

// Same behavior as the Angular datafilter pipe: match any field, case-insensitive.
const filtered = computed(() => {
  const text = filter.value.trim().toLowerCase()
  if (!text) return configurations.value
  return configurations.value.filter((c) =>
    Object.values(c).some((v) => String(v).toLowerCase().includes(text))
  )
})

const menuRef = ref<InstanceType<typeof Menu> | null>(null)
const menuItems = ref<MenuItem[]>([])

function openMenu(event: Event, configuration: Configuration) {
  menuItems.value = [
    { label: 'View', icon: 'pi pi-eye', command: () => router.push(`/configuration/${configuration.id}`) },
    { label: 'Deploy', icon: 'pi pi-play', command: () => router.push(`/deploy/${configuration.id}`) },
    {
      label: 'Deployments',
      icon: 'pi pi-external-link',
      command: () => router.push(`/deployments/${configuration.id}`)
    },
    { label: 'Remove', icon: 'pi pi-trash', command: () => confirmDelete(configuration.id) }
  ]
  menuRef.value?.toggle(event)
}

function confirmDelete(id: number) {
  confirm.require({
    header: 'Are you sure?',
    message: `You will remove Configuration ${id}`,
    accept: async () => {
      try {
        await deleteConfiguration(id)
        configurations.value = configurations.value.filter((c) => c.id !== id)
        notify.ok('Configuration deleted')
      } catch (err) {
        notify.error('Error deleting the configuration: ' + (err as Error).message)
      }
    }
  })
}
</script>

<template>
  <div class="page">
    <div class="page-header">
      <h1>Configurations</h1>
      <span class="spacer"></span>
      <router-link to="/configuration-create">
        <Button icon="pi pi-plus" rounded title="Add a configuration" />
      </router-link>
    </div>

    <div class="field">
      <InputText v-model="filter" placeholder="Filter" />
    </div>

    <Menu ref="menuRef" :model="menuItems" popup />

    <div class="card-grid">
      <Card v-for="configuration in filtered" :key="configuration.id" class="dashboard-card surface">
        <template #title>
          <div class="card-title-row">
            <div class="title">
              <h3>{{ configuration.name }}</h3>
              <h6>{{ configuration.description }}</h6>
            </div>
            <Button icon="pi pi-ellipsis-v" text @click="openMenu($event, configuration)" />
          </div>
        </template>
        <template #content>
          <h3>ML Models:</h3>
          <div v-for="model in configuration.ml_models" :key="model.id">
            <router-link :to="`/model/${model.id}`">
              <Button :label="model.name" size="small" outlined :title="`View/Edit Model ${model.id}`" />
            </router-link>
          </div>
          <h3>Deployments:</h3>
          <div v-for="deployment in configuration.deployments" :key="deployment.id">
            <router-link :to="`/results/${deployment.id}`">
              <Button
                :label="deployment.time"
                size="small"
                class="chip-deployed"
                :title="`View Deployment ${deployment.time}`"
              />
            </router-link>
          </div>
        </template>
      </Card>
    </div>
  </div>
</template>

// frontend/src/views/ConfigurationList.tsx
import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Eye, MoreVertical, Play, ExternalLink, Trash2, Plus } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { useConfirm } from '@/hooks/useConfirm'
import { getConfigurations, deleteConfiguration } from '@/api'
import { useNotify } from '@/notify'
import { formatDate } from '@/logic/format'
import type { Configuration } from '@/types'

export default function ConfigurationList() {
  const notify = useNotify()
  const navigate = useNavigate()
  const { confirm, dialog } = useConfirm()
  const [configurations, setConfigurations] = useState<Configuration[]>([])
  const [filter, setFilter] = useState('')

  useEffect(() => {
    getConfigurations()
      .then(setConfigurations)
      .catch(() => notify.error('Error connecting with the server'))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Same behavior as the old datafilter pipe: match any field, case-insensitive.
  const filtered = useMemo(() => {
    const text = filter.trim().toLowerCase()
    if (!text) return configurations
    return configurations.filter((c) => Object.values(c).some((v) => String(v).toLowerCase().includes(text)))
  }, [configurations, filter])

  function confirmDelete(id: number) {
    confirm({
      header: 'Are you sure?',
      message: `You will remove Configuration ${id}`,
      accept: async () => {
        try {
          await deleteConfiguration(id)
          setConfigurations((prev) => prev.filter((c) => c.id !== id))
          notify.ok('Configuration deleted')
        } catch (err) {
          notify.error('Error deleting the configuration: ' + (err as Error).message)
        }
      },
    })
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <h1 className="text-xl font-semibold">Configurations</h1>
        <span className="flex-1" />
        <Button size="icon" className="rounded-full" title="Add a configuration" asChild>
          <Link to="/configuration-create">
            <Plus className="size-4" />
          </Link>
        </Button>
      </div>

      <Input placeholder="Filter" value={filter} onChange={(e) => setFilter(e.target.value)} className="max-w-xs" />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {filtered.map((configuration) => (
          <Card key={configuration.id}>
            <CardHeader className="flex-row items-start justify-between gap-2 space-y-0">
              <div>
                <h3 className="font-semibold">{configuration.name}</h3>
                <p className="text-sm text-muted-foreground">{configuration.description}</p>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" size="icon">
                    <MoreVertical className="size-4" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem onClick={() => navigate(`/configuration/${configuration.id}`)}>
                    <Eye /> View
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => navigate(`/deploy/${configuration.id}`)}>
                    <Play /> Deploy
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => navigate(`/deployments/${configuration.id}`)}>
                    <ExternalLink /> Deployments
                  </DropdownMenuItem>
                  <DropdownMenuItem variant="destructive" onClick={() => confirmDelete(configuration.id)}>
                    <Trash2 /> Remove
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </CardHeader>
            <CardContent className="space-y-3">
              <div>
                <h4 className="mb-1.5 text-sm font-semibold">ML Models:</h4>
                <div className="flex flex-wrap gap-1.5">
                  {configuration.ml_models.map((model) => (
                    <Button key={model.id} variant="outline" size="sm" title={`View/Edit Model ${model.id}`} asChild>
                      <Link to={`/model/${model.id}`}>{model.name}</Link>
                    </Button>
                  ))}
                </div>
              </div>
              <div>
                <h4 className="mb-1.5 text-sm font-semibold">Deployments:</h4>
                <div className="flex flex-wrap gap-1.5">
                  {(configuration.deployments ?? []).map((deployment) => (
                    <Button
                      key={deployment.id}
                      variant="secondary"
                      size="sm"
                      title={`View Deployment ${formatDate(deployment.time)}`}
                      asChild
                    >
                      <Link to={`/results/${deployment.id}`}>{formatDate(deployment.time)}</Link>
                    </Button>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
      {dialog}
    </div>
  )
}
