// frontend/src/views/DeploymentList.tsx
import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Eye, Trash2, PencilLine, LogIn, Square, Check } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { useConfirm } from '@/hooks/useConfirm'
import { getDeployments, getDeploymentsOfConfiguration, getConfiguration, deleteDeployment } from '@/api'
import { useNotify } from '@/notify'
import { formatDate } from '@/logic/format'
import type { Configuration, DeploymentInfo, TrainingStatus } from '@/types'
import { cn } from '@/lib/utils'

const statusClass: Record<TrainingStatus, string> = {
  created: 'bg-secondary text-secondary-foreground',
  deployed: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
  stopped: 'bg-amber-500/15 text-amber-600 dark:text-amber-400',
  finished: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400',
}

// Same icon-per-status mapping ResultList.tsx uses - status here was
// previously conveyed by chip color alone, not colorblind-friendly and
// inconsistent with how the Training/Results table shows the same status.
const statusIcons: Record<TrainingStatus, typeof PencilLine> = {
  created: PencilLine,
  deployed: LogIn,
  stopped: Square,
  finished: Check,
}

export default function DeploymentList() {
  const { id } = useParams()
  const navigate = useNavigate()
  const notify = useNotify()
  const { confirm, dialog } = useConfirm()

  const configurationID = id ? Number(id) : undefined
  const [configuration, setConfiguration] = useState<Configuration | null>(null)
  const [deployments, setDeployments] = useState<DeploymentInfo[]>([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState('')

  useEffect(() => {
    async function load() {
      try {
        if (configurationID !== undefined) {
          setConfiguration(await getConfiguration(configurationID))
          setDeployments(await getDeploymentsOfConfiguration(configurationID))
        } else {
          setDeployments(await getDeployments())
        }
      } catch {
        notify.error('Error connecting with the server')
      } finally {
        setLoading(false)
      }
    }
    load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [configurationID])

  const filtered = useMemo(() => {
    const text = filter.trim().toLowerCase()
    if (!text) return deployments
    return deployments.filter((d) => Object.values(d).some((v) => String(v).toLowerCase().includes(text)))
  }, [deployments, filter])

  function confirmDelete(id: number) {
    confirm({
      header: 'Are you sure?',
      message: `You will remove Deployment ${id}`,
      accept: async () => {
        try {
          await deleteDeployment(id)
          setDeployments((prev) => prev.filter((d) => d.id !== id))
          notify.ok('Deployment deleted')
        } catch (err) {
          notify.error('Error deleting the deployment: ' + (err as Error).message)
        }
      },
    })
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <h1 className="text-xl font-semibold">
          Deployments
          {configuration && <span className="ml-2 text-base font-normal text-muted-foreground">of Configuration {configuration.name}</span>}
        </h1>
      </div>

      <Input placeholder="Filter" value={filter} onChange={(e) => setFilter(e.target.value)} className="max-w-xs" />

      {filtered.length === 0 && (
        <p className="py-8 text-center text-muted-foreground">{loading ? 'Loading…' : 'No deployments.'}</p>
      )}

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {filtered.map((deployment) => (
          <Card key={deployment.id}>
            <CardHeader className="flex-row items-start justify-between gap-2 space-y-0">
              <div>
                <h3 className="font-semibold">Deployment {deployment.id}</h3>
                <p className="text-sm text-muted-foreground">{formatDate(deployment.time)}</p>
              </div>
              <div className="flex gap-1">
                <Button variant="ghost" size="icon" title="Results" onClick={() => navigate(`/results/${deployment.id}`)}>
                  <Eye className="size-4" />
                </Button>
                <Button variant="ghost" size="icon" title="Remove" onClick={() => confirmDelete(deployment.id)}>
                  <Trash2 className="size-4" />
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-3 text-sm">
              <div>
                <h4 className="mb-1.5 font-semibold">Training results</h4>
                <div className="flex flex-col items-start gap-1.5">
                  {deployment.results.map((result) => {
                    const StatusIcon = statusIcons[result.status]
                    return (
                      <Button
                        key={result.id}
                        size="sm"
                        className={cn('h-auto max-w-full gap-1.5 py-1 whitespace-normal', statusClass[result.status])}
                        variant="secondary"
                        title={`Result ${result.id} - status: ${result.status}, last change: ${formatDate(result.status_changed)}`}
                        asChild
                      >
                        <Link to={`/results/${deployment.id}`}>
                          <StatusIcon className="size-3.5 shrink-0" />
                          Model {result.model.name}
                        </Link>
                      </Button>
                    )
                  })}
                </div>
              </div>
              <div>
                <h4 className="mb-1.5 font-semibold">Configuration:</h4>
                <Button variant="outline" size="sm" asChild>
                  <Link to={`/configuration/${deployment.configuration.id}`}>{deployment.configuration.name}</Link>
                </Button>
              </div>
              <div>
                <h4 className="font-semibold">Batch size:</h4>
                <p>{deployment.batch}</p>
              </div>
              {deployment.tf_kwargs_fit && (
                <div>
                  <h4 className="font-semibold">TF Training arguments:</h4>
                  <p>{deployment.tf_kwargs_fit}</p>
                </div>
              )}
              {deployment.tf_kwargs_val && (
                <div>
                  <h4 className="font-semibold">TF Validation arguments:</h4>
                  <p>{deployment.tf_kwargs_val}</p>
                </div>
              )}
              {deployment.pth_kwargs_fit && (
                <div>
                  <h4 className="font-semibold">PTH Training arguments:</h4>
                  <p>{deployment.pth_kwargs_fit}</p>
                </div>
              )}
              {deployment.pth_kwargs_val && (
                <div>
                  <h4 className="font-semibold">PTH Validation arguments:</h4>
                  <p>{deployment.pth_kwargs_val}</p>
                </div>
              )}
            </CardContent>
          </Card>
        ))}
      </div>
      {dialog}
    </div>
  )
}

// frontend/src/views/DeploymentList.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useConfirm } from 'primevue/useconfirm'
import Card from 'primevue/card'
import InputText from 'primevue/inputtext'
import Button from 'primevue/button'
import Menu from 'primevue/menu'
import type { MenuItem } from 'primevue/menuitem'
import {
  getDeployments,
  getDeploymentsOfConfiguration,
  getConfiguration,
  deleteDeployment
} from '../api'
import { useNotify } from '../notify'
import type { Configuration, DeploymentInfo } from '../types'

const route = useRoute()
const router = useRouter()
const notify = useNotify()
const confirm = useConfirm()

const configurationID = route.params.id ? Number(route.params.id) : undefined
const configuration = ref<Configuration | null>(null)
const deployments = ref<DeploymentInfo[]>([])
const filter = ref('')

onMounted(async () => {
  try {
    if (configurationID !== undefined) {
      configuration.value = await getConfiguration(configurationID)
      deployments.value = await getDeploymentsOfConfiguration(configurationID)
    } else {
      deployments.value = await getDeployments()
    }
  } catch {
    notify.error('Error connecting with the server')
  }
})

const filtered = computed(() => {
  const text = filter.value.trim().toLowerCase()
  if (!text) return deployments.value
  return deployments.value.filter((d) =>
    Object.values(d).some((v) => String(v).toLowerCase().includes(text))
  )
})

const menuRef = ref<InstanceType<typeof Menu> | null>(null)
const menuItems = ref<MenuItem[]>([])

function openMenu(event: Event, deployment: DeploymentInfo) {
  menuItems.value = [
    { label: 'Results', icon: 'pi pi-eye', command: () => router.push(`/results/${deployment.id}`) },
    { label: 'Remove', icon: 'pi pi-trash', command: () => confirmDelete(deployment.id) }
  ]
  menuRef.value?.toggle(event)
}

function confirmDelete(id: number) {
  confirm.require({
    header: 'Are you sure?',
    message: `You will remove Deployment ${id}`,
    accept: async () => {
      try {
        await deleteDeployment(id)
        deployments.value = deployments.value.filter((d) => d.id !== id)
        notify.ok('Deployment deleted')
      } catch (err) {
        notify.error('Error deleting the deployment: ' + (err as Error).message)
      }
    }
  })
}
</script>

<template>
  <div class="page">
    <div class="page-header">
      <h1>
        Deployments
        <span v-if="configuration" class="subtitle"> of Configuration {{ configuration.name }}</span>
      </h1>
    </div>

    <div class="field">
      <InputText v-model="filter" placeholder="Filter" />
    </div>

    <Menu ref="menuRef" :model="menuItems" popup />

    <div class="card-grid">
      <Card v-for="deployment in filtered" :key="deployment.id" class="dashboard-card surface">
        <template #title>
          <div class="card-title-row">
            <div class="title">
              <h3>Deployment {{ deployment.id }}</h3>
              <h6>{{ deployment.time }}</h6>
            </div>
            <Button icon="pi pi-ellipsis-v" text @click="openMenu($event, deployment)" />
          </div>
        </template>
        <template #content>
          <h3>Training results</h3>
          <div v-for="result in deployment.results" :key="result.id">
            <router-link :to="`/results/${deployment.id}`">
              <Button
                :label="`Model ${result.model.name}, last change ${result.status_changed}`"
                size="small"
                :class="`chip-${result.status}`"
                :title="`Result ${result.id} status ${result.status}`"
              />
            </router-link>
          </div>
          <h3>Configuration:</h3>
          <router-link :to="`/configuration/${deployment.configuration.id}`">
            <Button :label="deployment.configuration.name" size="small" outlined />
          </router-link>
          <h3>Batch size:</h3>
          <p>{{ deployment.batch }}</p>
          <template v-if="deployment.tf_kwargs_fit">
            <h3>TF Training arguments:</h3>
            <p>{{ deployment.tf_kwargs_fit }}</p>
          </template>
          <template v-if="deployment.tf_kwargs_val">
            <h3>TF Validation arguments:</h3>
            <p>{{ deployment.tf_kwargs_val }}</p>
          </template>
          <template v-if="deployment.pth_kwargs_fit">
            <h3>PTH Training arguments:</h3>
            <p>{{ deployment.pth_kwargs_fit }}</p>
          </template>
          <template v-if="deployment.pth_kwargs_val">
            <h3>PTH Validation arguments:</h3>
            <p>{{ deployment.pth_kwargs_val }}</p>
          </template>
        </template>
      </Card>
    </div>
  </div>
</template>
