// frontend/src/views/DeploymentView.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Card from 'primevue/card'
import InputText from 'primevue/inputtext'
import InputNumber from 'primevue/inputnumber'
import Checkbox from 'primevue/checkbox'
import RadioButton from 'primevue/radiobutton'
import Dropdown from 'primevue/dropdown'
import InputSwitch from 'primevue/inputswitch'
import Button from 'primevue/button'
import {
  getConfiguration,
  getFrameworksInConfiguration,
  getDistributedConfiguration,
  deploy
} from '../api'
import { enableFederatedBlockchain } from '../env'
import { useNotify } from '../notify'
import {
  KWARGS_RE,
  showIndefinite as showIndefiniteFn,
  showBlockchainToggle as showBlockchainToggleFn,
  showIndefiniteFields as showIndefiniteFieldsFn,
  isDeploymentFormInvalid,
  buildDeploymentPayload,
  type DeploymentForm
} from '../logic/deployment'
import type { Configuration } from '../types'

const route = useRoute()
const router = useRouter()
const notify = useNotify()

const configurationID = Number(route.params.id)
const configuration = ref<Partial<Configuration>>({})
const valid = ref(false)
const detectedFrameworks = ref<string[]>([])
const showDistributed = ref(false)

const strategies = [{ value: 'FedAvg', label: 'Federated Averaging strategy' }]

const form = ref<DeploymentForm>({
  unsupervised: false,
  incremental: false,
  federated: false,
  indefinite: false,
  blockchain: false,
  batch: null,
  tf_kwargs_fit: '',
  tf_kwargs_val: '',
  pth_kwargs_fit: '',
  pth_kwargs_val: '',
  unsupervised_rounds: null,
  confidence: null,
  optimizer: '',
  learning_rate: '',
  loss: '',
  metrics: '',
  stream_timeout: null,
  monitoring_metric: '',
  change: '',
  improvement: '',
  gpumem: null,
  agg_rounds: null,
  min_data: null,
  data_restriction: '',
  agg_strategy: null,
  conf_mat_settings: false
})

onMounted(async () => {
  try {
    configuration.value = await getConfiguration(configurationID)
    valid.value = true
    detectedFrameworks.value = await getFrameworksInConfiguration(configurationID)
    showDistributed.value = Boolean(await getDistributedConfiguration(configurationID))
  } catch {
    notify.error('Configuration not found')
  }
})

const hasTf = computed(() => detectedFrameworks.value.includes('tf'))
const hasPth = computed(() => detectedFrameworks.value.includes('pth'))
const showIndefinite = computed(() => showIndefiniteFn(form.value))
const showBlockchainToggle = computed(() =>
  showBlockchainToggleFn(form.value, enableFederatedBlockchain)
)
const showIndefiniteFields = computed(() => showIndefiniteFieldsFn(form.value))

const tfKwargsFitInvalid = computed(() => hasTf.value && !KWARGS_RE.test(form.value.tf_kwargs_fit || ''))
const tfKwargsValInvalid = computed(() => hasTf.value && !KWARGS_RE.test(form.value.tf_kwargs_val || ''))
const pthKwargsFitInvalid = computed(() => hasPth.value && !KWARGS_RE.test(form.value.pth_kwargs_fit || ''))
const pthKwargsValInvalid = computed(() => hasPth.value && !KWARGS_RE.test(form.value.pth_kwargs_val || ''))

const formInvalid = computed(() =>
  isDeploymentFormInvalid(form.value, {
    detectedFrameworks: detectedFrameworks.value,
    hasTf: hasTf.value,
    hasPth: hasPth.value
  })
)

async function onSubmit() {
  const payload = buildDeploymentPayload(form.value, {
    configurationID,
    showDistributed: showDistributed.value,
    enableFederatedBlockchain
  })
  try {
    await deploy(payload)
    router.push('/deployments')
  } catch (err) {
    notify.error('Error deploying the configuration: ' + (err as Error).message)
  }
}
</script>

<template>
  <div class="page">
    <Card class="form-card">
      <template #title>Deploy configuration {{ configuration.name }}</template>
      <template #content>
        <form @submit.prevent="onSubmit" autocomplete="off">
          <div class="field">
            <label><Checkbox v-model="form.unsupervised" binary /> Semi-supervised training</label>
          </div>
          <div class="field field-row">
            <label><Checkbox v-model="form.incremental" binary /> Incremental training</label>
            <label><Checkbox v-model="form.federated" binary /> Federated learning</label>
          </div>
          <div class="field" v-if="showIndefinite">
            <label><Checkbox v-model="form.indefinite" binary /> Indefinite training</label>
          </div>
          <div class="field" v-if="showBlockchainToggle">
            <label><Checkbox v-model="form.blockchain" binary /> Blockchain-traced training</label>
          </div>

          <h4>Model training settings</h4>

          <div class="field" v-if="detectedFrameworks.length > 0">
            <label>Batch size for training *</label>
            <InputNumber v-model="form.batch" placeholder="10" :useGrouping="false" />
          </div>

          <template v-if="hasTf">
            <div class="field">
              <label>TensorFlow Training configuration *</label>
              <InputText v-model="form.tf_kwargs_fit" placeholder="epochs=5" />
              <span class="text-danger" v-if="form.tf_kwargs_fit && tfKwargsFitInvalid">
                Use the format: key=value, key=value
              </span>
            </div>
            <div class="field">
              <label>TensorFlow Validation configuration</label>
              <InputText v-model="form.tf_kwargs_val" />
              <span class="text-danger" v-if="form.tf_kwargs_val && tfKwargsValInvalid">
                Use the format: key=value, key=value
              </span>
            </div>
          </template>

          <template v-if="hasPth">
            <div class="field">
              <label>PyTorch Training configuration *</label>
              <InputText v-model="form.pth_kwargs_fit" placeholder="max_epochs=5" />
            </div>
            <div class="field">
              <label>PyTorch Validation configuration</label>
              <InputText v-model="form.pth_kwargs_val" />
            </div>
          </template>

          <template v-if="form.unsupervised">
            <h4>Unsupervised models settings</h4>
            <div class="field" v-if="!form.incremental">
              <label>Unsupervised rounds</label>
              <InputNumber v-model="form.unsupervised_rounds" placeholder="5" :useGrouping="false" />
            </div>
            <div class="field">
              <label>Confidence</label>
              <InputNumber
                v-model="form.confidence"
                placeholder="0.9"
                :maxFractionDigits="5"
                :useGrouping="false"
              />
            </div>
          </template>

          <template v-if="showDistributed">
            <h4>Distributed models settings</h4>
            <div class="field">
              <label>Optimizer</label>
              <InputText v-model="form.optimizer" placeholder="adam" />
            </div>
            <div class="field">
              <label>Learning rate</label>
              <InputText v-model="form.learning_rate as string" placeholder="0.001" />
            </div>
            <div class="field">
              <label>Loss function</label>
              <InputText v-model="form.loss" placeholder="sparse_categorical_crossentropy" />
            </div>
            <div class="field">
              <label>Metrics (splitted by comas)</label>
              <InputText v-model="form.metrics" placeholder="sparse_categorical_accuracy" />
            </div>
          </template>

          <template v-if="form.incremental">
            <h4>Incremental training settings</h4>
            <div class="field" v-if="!form.indefinite">
              <label>Stream timeout (in milliseconds)</label>
              <InputNumber v-model="form.stream_timeout" placeholder="60000" :useGrouping="false" />
            </div>
            <template v-if="showIndefiniteFields">
              <div class="field">
                <label>Monitoring metric (must match with a predefined metric) *</label>
                <InputText v-model="form.monitoring_metric" />
              </div>
              <div class="field">
                <label>If the monitoring metric improves, does it increase or decrease? *</label>
                <div class="field-row">
                  <label><RadioButton v-model="form.change" value="up" /> Increase</label>
                  <label><RadioButton v-model="form.change" value="down" /> Decrease</label>
                </div>
              </div>
              <div class="field">
                <label>Improvement</label>
                <InputText v-model="form.improvement as string" placeholder="0.05" />
              </div>
            </template>
          </template>

          <div class="field" v-if="detectedFrameworks.length > 0">
            <label>GPU Memory usage estimation in GB (Kubernetes Scheduler) *</label>
            <InputNumber v-model="form.gpumem" placeholder="0" :useGrouping="false" />
          </div>

          <template v-if="form.federated">
            <h4>Federated strategy settings</h4>
            <div class="field">
              <label>Number of aggregation rounds *</label>
              <InputNumber v-model="form.agg_rounds" placeholder="15" :useGrouping="false" />
            </div>
            <div class="field" v-if="!form.incremental">
              <label>Minimun data entries per device *</label>
              <InputNumber v-model="form.min_data" placeholder="1000" :useGrouping="false" />
            </div>
            <div class="field">
              <label>Data Restriction *</label>
              <InputText v-model="form.data_restriction" placeholder="{}" />
            </div>
            <div class="field">
              <label>Aggregation strategy *</label>
              <Dropdown
                v-model="form.agg_strategy"
                :options="strategies"
                optionValue="value"
                optionLabel="label"
              />
            </div>
          </template>

          <div
            class="field"
            v-if="detectedFrameworks.length > 0 && !form.incremental && !form.federated"
          >
            <label style="display: flex; align-items: center; gap: 0.6rem">
              <InputSwitch v-model="form.conf_mat_settings" />
              Create confusion matrix at end (if test set is specified)
            </label>
          </div>

          <div class="row-buttons">
            <Button label="Go Back" text @click="$router.back()" />
            <Button v-if="valid" type="submit" label="Deploy" :disabled="formInvalid" />
          </div>
        </form>
      </template>
    </Card>
  </div>
</template>

// frontend/src/views/DeploymentView.tsx
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Separator } from '@/components/ui/separator'
import { getConfiguration, getFrameworksInConfiguration, getDistributedConfiguration, deploy } from '@/api'
import { enableFederatedBlockchain } from '@/env'
import { useNotify } from '@/notify'
import {
  KWARGS_RE,
  showIndefinite as showIndefiniteFn,
  showBlockchainToggle as showBlockchainToggleFn,
  showIndefiniteFields as showIndefiniteFieldsFn,
  isDeploymentFormInvalid,
  buildDeploymentPayload,
  type DeploymentForm,
} from '@/logic/deployment'
import type { Configuration } from '@/types'

const strategies = [{ value: 'FedAvg', label: 'Federated Averaging strategy' }]

const initialForm: DeploymentForm = {
  unsupervised: false,
  incremental: false,
  federated: false,
  indefinite: false,
  blockchain: false,
  batch: null,
  tf_kwargs_fit: '',
  tf_kwargs_val: '',
  pth_kwargs_fit: '',
  pth_kwargs_val: '',
  unsupervised_rounds: null,
  confidence: null,
  optimizer: '',
  learning_rate: '',
  loss: '',
  metrics: '',
  stream_timeout: null,
  monitoring_metric: '',
  change: '',
  improvement: '',
  gpumem: null,
  agg_rounds: null,
  min_data: null,
  data_restriction: '',
  agg_strategy: null,
  conf_mat_settings: false,
}

function numberOrNull(v: string): number | null {
  if (v === '') return null
  const n = Number(v)
  return Number.isNaN(n) ? null : n
}

export default function DeploymentView() {
  const { id } = useParams()
  const navigate = useNavigate()
  const notify = useNotify()

  const configurationID = Number(id)
  const [configuration, setConfiguration] = useState<Partial<Configuration>>({})
  const [valid, setValid] = useState(false)
  const [detectedFrameworks, setDetectedFrameworks] = useState<string[]>([])
  const [showDistributed, setShowDistributed] = useState(false)
  const [form, setForm] = useState<DeploymentForm>(initialForm)

  useEffect(() => {
    let cancelled = false
    async function load() {
      try {
        const config = await getConfiguration(configurationID)
        if (cancelled) return
        setConfiguration(config)
        setValid(true)
        const frameworks = await getFrameworksInConfiguration(configurationID)
        if (cancelled) return
        setDetectedFrameworks(frameworks)
        const distributed = await getDistributedConfiguration(configurationID)
        if (!cancelled) setShowDistributed(Boolean(distributed))
      } catch {
        if (!cancelled) notify.error('Configuration not found')
      }
    }
    load()
    return () => {
      cancelled = true
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [configurationID])

  const hasTf = detectedFrameworks.includes('tf')
  const hasPth = detectedFrameworks.includes('pth')
  const showIndefinite = showIndefiniteFn(form)
  const showBlockchainToggle = showBlockchainToggleFn(form, enableFederatedBlockchain)
  const showIndefiniteFields = showIndefiniteFieldsFn(form)

  const tfKwargsFitInvalid = hasTf && !KWARGS_RE.test(form.tf_kwargs_fit || '')
  const tfKwargsValInvalid = hasTf && !KWARGS_RE.test(form.tf_kwargs_val || '')

  const formInvalid = isDeploymentFormInvalid(form, { detectedFrameworks, hasTf, hasPth })

  function set<K extends keyof DeploymentForm>(key: K, value: DeploymentForm[K]) {
    setForm((prev) => ({ ...prev, [key]: value }))
  }

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault()
    const payload = buildDeploymentPayload(form, {
      configurationID,
      showDistributed,
      enableFederatedBlockchain,
    })
    try {
      await deploy(payload)
      navigate('/deployments')
    } catch (err) {
      notify.error('Error deploying the configuration: ' + (err as Error).message)
    }
  }

  return (
    <div className="mx-auto max-w-2xl">
      <Card>
        <CardHeader>
          <CardTitle>Deploy configuration {configuration.name}</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} autoComplete="off" className="space-y-5">
            <label className="flex items-center gap-2 text-sm font-normal">
              <Checkbox
                checked={form.unsupervised}
                onCheckedChange={(v) => set('unsupervised', v === true)}
              />
              Semi-supervised training
            </label>
            <div className="flex gap-6">
              <label className="flex items-center gap-2 text-sm font-normal">
                <Checkbox checked={form.incremental} onCheckedChange={(v) => set('incremental', v === true)} />
                Incremental training
              </label>
              <label className="flex items-center gap-2 text-sm font-normal">
                <Checkbox checked={form.federated} onCheckedChange={(v) => set('federated', v === true)} />
                Federated learning
              </label>
            </div>
            {showIndefinite && (
              <label className="flex items-center gap-2 text-sm font-normal">
                <Checkbox checked={form.indefinite} onCheckedChange={(v) => set('indefinite', v === true)} />
                Indefinite training
              </label>
            )}
            {showBlockchainToggle && (
              <label className="flex items-center gap-2 text-sm font-normal">
                <Checkbox checked={form.blockchain} onCheckedChange={(v) => set('blockchain', v === true)} />
                Blockchain-traced training
              </label>
            )}

            <Separator />
            <h4 className="font-semibold">Model training settings</h4>

            {detectedFrameworks.length > 0 && (
              <div className="space-y-1.5">
                <Label>Batch size for training *</Label>
                <Input
                  type="number"
                  placeholder="10"
                  value={form.batch ?? ''}
                  onChange={(e) => set('batch', numberOrNull(e.target.value))}
                />
              </div>
            )}

            {hasTf && (
              <>
                <div className="space-y-1.5">
                  <Label>TensorFlow Training configuration *</Label>
                  <Input
                    placeholder="epochs=5"
                    value={form.tf_kwargs_fit}
                    onChange={(e) => set('tf_kwargs_fit', e.target.value)}
                  />
                  {form.tf_kwargs_fit && tfKwargsFitInvalid && (
                    <p className="text-sm text-destructive">Use the format: key=value, key=value</p>
                  )}
                </div>
                <div className="space-y-1.5">
                  <Label>TensorFlow Validation configuration</Label>
                  <Input value={form.tf_kwargs_val} onChange={(e) => set('tf_kwargs_val', e.target.value)} />
                  {form.tf_kwargs_val && tfKwargsValInvalid && (
                    <p className="text-sm text-destructive">Use the format: key=value, key=value</p>
                  )}
                </div>
              </>
            )}

            {hasPth && (
              <>
                <div className="space-y-1.5">
                  <Label>PyTorch Training configuration *</Label>
                  <Input
                    placeholder="max_epochs=5"
                    value={form.pth_kwargs_fit}
                    onChange={(e) => set('pth_kwargs_fit', e.target.value)}
                  />
                </div>
                <div className="space-y-1.5">
                  <Label>PyTorch Validation configuration</Label>
                  <Input value={form.pth_kwargs_val} onChange={(e) => set('pth_kwargs_val', e.target.value)} />
                </div>
              </>
            )}

            {form.unsupervised && (
              <>
                <Separator />
                <h4 className="font-semibold">Unsupervised models settings</h4>
                {!form.incremental && (
                  <div className="space-y-1.5">
                    <Label>Unsupervised rounds</Label>
                    <Input
                      type="number"
                      placeholder="5"
                      value={form.unsupervised_rounds ?? ''}
                      onChange={(e) => set('unsupervised_rounds', numberOrNull(e.target.value))}
                    />
                  </div>
                )}
                <div className="space-y-1.5">
                  <Label>Confidence</Label>
                  <Input
                    type="number"
                    step="0.00001"
                    placeholder="0.9"
                    value={form.confidence ?? ''}
                    onChange={(e) => set('confidence', numberOrNull(e.target.value))}
                  />
                </div>
              </>
            )}

            {showDistributed && (
              <>
                <Separator />
                <h4 className="font-semibold">Distributed models settings</h4>
                <div className="space-y-1.5">
                  <Label>Optimizer</Label>
                  <Input placeholder="adam" value={form.optimizer} onChange={(e) => set('optimizer', e.target.value)} />
                </div>
                <div className="space-y-1.5">
                  <Label>Learning rate</Label>
                  <Input
                    placeholder="0.001"
                    value={form.learning_rate ?? ''}
                    onChange={(e) => set('learning_rate', e.target.value)}
                  />
                </div>
                <div className="space-y-1.5">
                  <Label>Loss function</Label>
                  <Input
                    placeholder="sparse_categorical_crossentropy"
                    value={form.loss}
                    onChange={(e) => set('loss', e.target.value)}
                  />
                </div>
                <div className="space-y-1.5">
                  <Label>Metrics (splitted by comas)</Label>
                  <Input
                    placeholder="sparse_categorical_accuracy"
                    value={form.metrics}
                    onChange={(e) => set('metrics', e.target.value)}
                  />
                </div>
              </>
            )}

            {form.incremental && (
              <>
                <Separator />
                <h4 className="font-semibold">Incremental training settings</h4>
                {!form.indefinite && (
                  <div className="space-y-1.5">
                    <Label>Stream timeout (in milliseconds)</Label>
                    <Input
                      type="number"
                      placeholder="60000"
                      value={form.stream_timeout ?? ''}
                      onChange={(e) => set('stream_timeout', numberOrNull(e.target.value))}
                    />
                  </div>
                )}
                {showIndefiniteFields && (
                  <>
                    <div className="space-y-1.5">
                      <Label>Monitoring metric (must match with a predefined metric) *</Label>
                      <Input value={form.monitoring_metric} onChange={(e) => set('monitoring_metric', e.target.value)} />
                    </div>
                    <div className="space-y-2">
                      <Label>If the monitoring metric improves, does it increase or decrease? *</Label>
                      <RadioGroup
                        value={form.change}
                        onValueChange={(v) => set('change', v as DeploymentForm['change'])}
                        className="flex gap-6"
                      >
                        <label className="flex items-center gap-2 text-sm font-normal">
                          <RadioGroupItem value="up" /> Increase
                        </label>
                        <label className="flex items-center gap-2 text-sm font-normal">
                          <RadioGroupItem value="down" /> Decrease
                        </label>
                      </RadioGroup>
                    </div>
                    <div className="space-y-1.5">
                      <Label>Improvement</Label>
                      <Input
                        placeholder="0.05"
                        value={form.improvement ?? ''}
                        onChange={(e) => set('improvement', e.target.value)}
                      />
                    </div>
                  </>
                )}
              </>
            )}

            {detectedFrameworks.length > 0 && (
              <div className="space-y-1.5">
                <Label>GPU Memory usage estimation in GB (Kubernetes Scheduler) *</Label>
                <Input
                  type="number"
                  placeholder="0"
                  value={form.gpumem ?? ''}
                  onChange={(e) => set('gpumem', numberOrNull(e.target.value))}
                />
              </div>
            )}

            {form.federated && (
              <>
                <Separator />
                <h4 className="font-semibold">Federated strategy settings</h4>
                <div className="space-y-1.5">
                  <Label>Number of aggregation rounds *</Label>
                  <Input
                    type="number"
                    placeholder="15"
                    value={form.agg_rounds ?? ''}
                    onChange={(e) => set('agg_rounds', numberOrNull(e.target.value))}
                  />
                </div>
                {!form.incremental && (
                  <div className="space-y-1.5">
                    <Label>Minimun data entries per device *</Label>
                    <Input
                      type="number"
                      placeholder="1000"
                      value={form.min_data ?? ''}
                      onChange={(e) => set('min_data', numberOrNull(e.target.value))}
                    />
                  </div>
                )}
                <div className="space-y-1.5">
                  <Label>Data Restriction *</Label>
                  <Input placeholder="{}" value={form.data_restriction} onChange={(e) => set('data_restriction', e.target.value)} />
                </div>
                <div className="space-y-1.5">
                  <Label>Aggregation strategy *</Label>
                  <Select value={form.agg_strategy ?? undefined} onValueChange={(v) => set('agg_strategy', v)}>
                    <SelectTrigger className="w-full">
                      <SelectValue placeholder="Select a strategy" />
                    </SelectTrigger>
                    <SelectContent>
                      {strategies.map((s) => (
                        <SelectItem key={s.value} value={s.value}>
                          {s.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </>
            )}

            {detectedFrameworks.length > 0 && !form.incremental && !form.federated && (
              <label className="flex items-center gap-2 text-sm font-normal">
                <Switch checked={form.conf_mat_settings} onCheckedChange={(v) => set('conf_mat_settings', v)} />
                Create confusion matrix at end (if test set is specified)
              </label>
            )}

            <div className="flex justify-between border-t pt-4">
              <Button type="button" variant="ghost" onClick={() => navigate(-1)}>
                Go Back
              </Button>
              {valid && (
                <Button type="submit" disabled={formInvalid}>
                  Deploy
                </Button>
              )}
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}
