// frontend/src/views/IoTDeviceList.tsx
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import type { ColumnDef } from '@tanstack/react-table'
import { CloudUpload, CloudDownload, Copy, Pencil, Plus, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import DataTable from '@/components/DataTable'
import { useConfirm } from '@/hooks/useConfirm'
import { getIoTDevices, deleteIoTDevice } from '@/api'
import { useNotify } from '@/notify'
import type { IoTDevice } from '@/types'

export default function IoTDeviceList() {
  const notify = useNotify()
  const { confirm, dialog } = useConfirm()
  const [devices, setDevices] = useState<IoTDevice[]>([])

  useEffect(() => {
    getIoTDevices()
      .then(setDevices)
      .catch(() => notify.error('Error connecting with the server'))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  async function copyToClipboard(text: string) {
    try {
      await navigator.clipboard.writeText(text)
      notify.ok('Copied to clipboard')
    } catch (err) {
      notify.error('Error copying to clipboard: ' + err)
    }
  }

  function confirmDelete(id: number, token: string) {
    confirm({
      header: 'Are you sure?',
      message: `You will remove Device ${token}`,
      accept: async () => {
        try {
          await deleteIoTDevice(id)
          setDevices((prev) => prev.filter((d) => d.id !== id))
          notify.ok('Device deleted')
        } catch (err) {
          notify.error('Error deleting the device: ' + (err as Error).message)
        }
      },
    })
  }

  const columns: ColumnDef<IoTDevice, unknown>[] = [
    { accessorKey: 'token', header: 'MQTT ID' },
    { accessorKey: 'friendly_name', header: 'Friendly Name' },
    {
      id: 'broker',
      header: 'MQTT Broker',
      enableSorting: false,
      cell: ({ row }) => `${row.original.mqtt_address}:${row.original.mqtt_port}`,
    },
    {
      id: 'configuration',
      header: 'Configuration',
      enableSorting: false,
      cell: ({ row }) => (
        <Button variant="ghost" size="icon" title="Copy configuration" onClick={() => copyToClipboard(row.original.backlog)}>
          <Copy className="size-4" />
        </Button>
      ),
    },
    {
      accessorKey: 'status',
      header: 'Status',
      enableSorting: false,
      cell: ({ row }) =>
        row.original.status === 'connected' ? (
          <CloudUpload className="size-4 text-emerald-500" aria-label="connected" />
        ) : (
          <CloudDownload className="size-4 text-muted-foreground" aria-label="disconnected" />
        ),
    },
    {
      id: 'actions',
      header: 'Actions',
      enableSorting: false,
      cell: ({ row }) => (
        <div className="flex gap-1">
          <Button variant="ghost" size="icon" title="View/edit device" asChild>
            <Link to={`/device/${row.original.id}`}>
              <Pencil className="size-4" />
            </Link>
          </Button>
          <Button
            variant="ghost"
            size="icon"
            title="Delete device"
            onClick={() => confirmDelete(row.original.id, row.original.token)}
          >
            <Trash2 className="size-4" />
          </Button>
        </div>
      ),
    },
  ]

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <h1 className="text-xl font-semibold">Tasmota ML-Enabled IoT Devices</h1>
        <span className="flex-1" />
        <Button size="icon" className="rounded-full" title="Add a new device" asChild>
          <Link to="/devices-create">
            <Plus className="size-4" />
          </Link>
        </Button>
      </div>

      <DataTable columns={columns} data={devices} getRowId={(d) => String(d.id)} />
      {dialog}
    </div>
  )
}

// frontend/src/views/IoTDeviceList.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useConfirm } from 'primevue/useconfirm'
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'
import InputText from 'primevue/inputtext'
import Button from 'primevue/button'
import { FilterMatchMode } from 'primevue/api'
import { getIoTDevices, deleteIoTDevice } from '../api'
import { useNotify } from '../notify'
import type { IoTDevice } from '../types'

const notify = useNotify()
const confirm = useConfirm()

const devices = ref<IoTDevice[]>([])
const filters = ref({ global: { value: null as string | null, matchMode: FilterMatchMode.CONTAINS } })

onMounted(async () => {
  try {
    devices.value = await getIoTDevices()
  } catch {
    notify.error('Error connecting with the server')
  }
})

async function copyToClipboard(text: string) {
  try {
    await navigator.clipboard.writeText(text)
    notify.ok('Copied to clipboard')
  } catch (err) {
    notify.error('Error copying to clipboard: ' + err)
  }
}

function confirmDelete(id: number, token: string) {
  confirm.require({
    header: 'Are you sure?',
    message: `You will remove Device ${token}`,
    accept: async () => {
      try {
        await deleteIoTDevice(id)
        devices.value = devices.value.filter((d) => d.id !== id)
        notify.ok('Device deleted')
      } catch (err) {
        notify.error('Error deleting the device: ' + (err as Error).message)
      }
    }
  })
}
</script>

<template>
  <div class="page">
    <div class="page-header">
      <h1>Tasmota ML-Enabled IoT Devices</h1>
      <span class="spacer"></span>
      <router-link to="/devices-create">
        <Button icon="pi pi-plus" rounded title="Add a new device" />
      </router-link>
    </div>

    <DataTable :value="devices" v-model:filters="filters" paginator :rows="10" dataKey="id" class="surface">
      <template #header>
        <InputText v-model="filters.global.value" placeholder="Filter" />
      </template>
      <Column field="token" header="MQTT ID" sortable />
      <Column field="friendly_name" header="Friendly Name" sortable />
      <Column header="MQTT Broker">
        <template #body="{ data }">{{ data.mqtt_address }}:{{ data.mqtt_port }}</template>
      </Column>
      <Column header="Configuration">
        <template #body="{ data }">
          <Button
            icon="pi pi-copy"
            text
            title="Copy configuration"
            @click="copyToClipboard(data.backlog)"
          />
        </template>
      </Column>
      <Column field="status" header="Status">
        <template #body="{ data }">
          <i
            v-if="data.status === 'connected'"
            class="pi pi-cloud-upload status-connected"
            title="connected"
          ></i>
          <i
            v-if="data.status === 'disconnected'"
            class="pi pi-cloud-download status-disconnected"
            title="disconnected"
          ></i>
        </template>
      </Column>
      <Column header="Actions">
        <template #body="{ data }">
          <router-link :to="`/device/${data.id}`">
            <Button icon="pi pi-pencil" text title="View/edit device" />
          </router-link>
          <Button
            icon="pi pi-trash"
            text
            title="Delete device"
            @click="confirmDelete(data.id, data.token)"
          />
        </template>
      </Column>
    </DataTable>
  </div>
</template>
